#include "global_common.h"
#include "interior/options.h"

namespace interior {

std::string_view UsageText() noexcept
{
    // The block is aligned by hand; the formatter would set it against the literal after the name instead.
    // clang-format off
    return DSCREEN_PRODUCT_NAME
           " - DLSS 5 Neural Rendering for the live desktop\n"
           "\n"
           "Usage: " DSCREEN_FILE_STEM ".exe [options]\n"
           "\n"
           "Capture and output\n"
           "  --list-monitors            List monitors and exit\n"
           "  --monitor primary|all|N    Source: the primary monitor (default), every monitor, or monitor N\n"
           "  --window TITLE|0xHANDLE    Work on one window instead of a monitor: the first visible one whose title\n"
           "                             contains TITLE, ignoring case, or the window with that handle. The\n"
           "                             panel picks one by dragging a crosshair onto it. The capture follows\n"
           "                             it as it moves and gets its content even when something is in front\n"
           "                             of it; resizing it needs a new session, since the sizes are fixed\n"
           "  --target N                 Present on monitor N instead of the source monitor (enables upscaling)\n"
           "  --cursor auto|on|off       Include the cursor in the capture (auto: only when --target differs)\n"
           "  --capture-border on|off    Let Windows draw its capture border (default off)\n"
           "  --vsync on|off             Present synchronised to the display (default off)\n"
           "  --compare off|split|original\n"
           "                             Comparison view: split screen or the untouched capture\n"
           "  --format rgba8|rgba16f     Model colour format (default rgba8)\n"
           "\n"
           "DLSS 5 Neural Rendering (NGX feature 18, nvngx_dlssnr.dll)\n"
           "  --nr on|off                Run the neural rendering model (default on)\n"
           "  --nr-preset N              Weights to ask the model for (default 1, the only one the 310.8\n"
           "                             model carries; anything else falls back to it and says so). The\n"
           "                             panel offers this only when the model says how many it has\n"
           "  --nr-intensity F           How much of the model's work to keep, 1 being all of it (default 1). TEST\n"
           "                             BUILD: any finite value is passed to the model, above 1 and below 0 included\n"
           "  --nr-style 0|1|2           0 standard, 1 natural, 2 cinematic\n"
           "  --nr-local-structure F     Local structure strength (default 1)\n"
           "  --nr-local-tone F          Local tone strength (default 1)\n"
           "  --nr-skin F                Skin structure strength, 0 upwards; -1 exactly means follow local structure\n"
           "                             (default), and nothing between -1 and 0 means anything, so the panel\n"
           "                             offers that value as a switch. This and --nr-local-structure do\n"
           "                             nothing while --nr-automask is off\n"
           "  --nr-automask on|off       Let the model detect skin itself (default on)\n"
           "  --nr-ui-correction on|off  Model UI correction (default on). The model reads a UI layer that\n"
           "                             this app does not give it, so this is inert as wired\n"
           "  --nr-passes N              Run the model on its own output N times a frame (default 1).\n"
           "                             Each pass runs the whole model again, with a history of its own, on\n"
           "                             the picture the pass before it made: three passes cost three times\n"
           "                             one and the picture falls three times as far behind. Experimental\n"
           "\n"
           "DLSS Super Resolution (NGX feature 1, nvngx_dlss.dll)\n"
           "  --sr auto|dlaa|off         auto: upscale when the target differs from the source (default);\n"
           "                             dlaa: also run DLAA at 1:1 before neural rendering; off: never.\n"
           "                             Needs nvngx_dlss.dll, which NVIDIA ships separately: games carry a copy,\n"
           "                             the DLSS SDK has one, and recent drivers keep one of their own. A machine\n"
           "                             that does not offer super resolution turns this off rather than stopping\n"
           "                             the session, and the panel says so beside a warning glyph\n"
           "  --sr-preset N              DLSS render preset hint (0 = default)\n"
           "\n"
           "Motion vectors and depth (the desktop has neither, so they are synthesised)\n"
           "  --mv builtin|nvof|none     builtin: GPU block matching (default); nvof: NVIDIA Optical Flow\n"
           "                             hardware (needs a build with DSCREEN_ENABLE_NVOF); none: zero motion\n"
           "  --mv-level 0..7            Finest matching level: 0 full, 1 half (default), 2 quarter resolution\n"
           "  --nvof-grid 1|2|4          Optical Flow output grid (default 1)\n"
           "  --nvof-perf slow|medium|fast\n"
           "  --depth-value F            Constant depth plane value 0..1 (default 0.5)\n"
           "  --depth-inverted on|off    Tell the model the depth plane counts the other way (default off)\n"
           "  --mv-scale-x F             What the model multiplies the horizontal motion by; any finite value.\n"
           "                             Left out, it is the ratio between the model's size and the capture's\n"
           "  --mv-scale-y F             The same for the vertical motion\n"
           "  --reset-threshold F        Fraction of unmatched pixels that resets model history (default 0.5)\n"
           "\n"
           "NGX runtime\n"
           "  --ngx-path DIR             Extra folder searched for nvngx_dlssnr.dll / nvngx_dlss.dll\n"
           "  --ngx-app-id HEX           Initialise NGX with an application id instead of a project id\n"
           "  --ngx-project-id GUID      Project id used with NVSDK_NGX_D3D12_Init_with_ProjectID\n"
           "  --ngx-log 0|1|2            NGX logging: off (default), on, verbose. Off keeps NGX from writing\n"
           "                             its own log files beside the executable; on and verbose let it\n"
           "  --indicator on|off         Let the model draw its own overlay naming its version, the preset\n"
           "                             it resolved and its working size (default off; read only at start-up)\n"
           "  --cubin-cache on|off       Let the model cache its compiled kernels (default on; start-up only)\n"
           "  --app-data DIR             Folder for the NGX logs --ngx-log asks for, and for the model's\n"
           "                             kernel cache (default: next to the executable)\n"
           "\n"
           "Window and diagnostics\n"
           "  --affinity on|off          Exclude the output window from capture (default on; off makes the window\n"
           "                             photograph its own output, so the panel does not offer it). Nothing is\n"
           "                             hidden when the output is on a monitor that is not being captured, since\n"
           "                             nothing of ours can reach that capture\n"
           "  --topmost on|off           Keep the control panel above other windows (default off). The output\n"
           "                             window is always above everything\n"
           "  --click-through on|off     Pass mouse input through to the desktop beneath (default on; off makes the\n"
           "                             overlay swallow every click, so the panel does not offer it)\n"
           "  --redirection-bitmap on|off\n"
           "                             Give the window a GDI redirection surface (default off; diagnostic)\n"
           "  --adapter N                DXGI adapter index (default: first NVIDIA adapter). The panel lists the\n"
           "                             adapters it found by name rather than asking for an index\n"
           "  --debug-layer on|off       Enable the Direct3D 12 debug layer\n"
           "  --log-level 0..3           0 debug, 1 info (default), 2 warn, 3 error\n"
           "  --log-file PATH            Mirror the log to a file\n"
           "  --gui on|off               Open the control panel (default on; off leaves the overlay alone)\n"
           "  --console auto|on|off      auto: use the console it was launched from, none when there is\n"
           "                             none (a double-click opens no window); on: always make one\n"
           "  --exclude-own-windows on|off\n"
           "                             Ask the capture to leave this program's own windows out by name,\n"
           "                             instead of hiding them from every capture on the machine. Needs a\n"
           "                             Windows that offers it; where it works, the overlay and the panel\n"
           "                             can be screenshotted and recorded (default on for this branch)\n"
           "  --exclusion-log on|off     Write the capture-exclusion notes to\n"
           "                             " DSCREEN_FILE_STEM "-exclusion.log beside the executable\n"
           "                             (default off). They say what the capture was asked to leave out and\n"
           "                             what it answered, which is what to send if the overlay feeds back\n"
           "                             into its own capture\n"
           "  --show-inert on|off        Add an Inert page to the panel holding the settings that change\n"
           "                             nothing on a desktop: the depth plane and its inversion, model UI\n"
           "                             correction, and the two optical flow settings (default off)\n"
           "\n"
           "Every failure stops the program with a message; there are no silent fallbacks.\n"
           "\n"
           "Hotkeys (global, registered with RegisterHotKey)\n"
           "  Ctrl+Alt+Shift+O           Toggle between the processed and the original picture\n"
           "  Ctrl+Alt+Shift+C           Toggle the split comparison view\n"
           "  Ctrl+Alt+Shift+Q           Quit\n"
           "  Ctrl+Alt+Shift + mouse     Drag the split divider; no click, so the desktop keeps its input\n";
    // clang-format on
}

} // namespace interior
