#include "interior/options.h"

namespace interior {

std::string_view UsageText() noexcept
{
    return "DlssScreen - DLSS 5 Neural Rendering for the live desktop\n"
           "\n"
           "Usage: DlssScreen.exe [options]\n"
           "\n"
           "Capture and output\n"
           "  --list-monitors            List monitors and exit\n"
           "  --monitor primary|all|N    Source: the primary monitor (default), every monitor, or monitor N\n"
           "  --target N                 Present on monitor N instead of the source monitor (enables upscaling)\n"
           "  --cursor auto|on|off       Include the cursor in the capture (auto: only when --target differs)\n"
           "  --capture-border on|off    Let Windows draw its capture border (default off)\n"
           "  --vsync on|off             Present synchronised to the display (default on)\n"
           "  --compare off|split|original\n"
           "                             Comparison view: split screen or the untouched capture\n"
           "  --format rgba8|rgba16f     Model colour format (default rgba8)\n"
           "\n"
           "DLSS 5 Neural Rendering (NGX feature 18, nvngx_dlssnr.dll)\n"
           "  --nr on|off                Run the neural rendering model (default on)\n"
           "  --nr-preset 0..3           Model preset hint (0 = model default)\n"
           "  --nr-intensity F           Effect strength, 1 is the model default; any finite value is accepted\n"
           "  --nr-style 0|1|2           0 standard, 1 natural, 2 cinematic\n"
           "  --nr-local-structure F     Local structure strength (default 1)\n"
           "  --nr-local-tone F          Local tone strength (default 1)\n"
           "  --nr-skin F                Skin structure strength; -1 follows local structure (default)\n"
           "  --nr-automask on|off       Let the model detect skin itself (default on)\n"
           "  --nr-ui-correction on|off  Model UI correction (default on)\n"
           "\n"
           "DLSS Super Resolution (NGX feature 1, nvngx_dlss.dll)\n"
           "  --sr auto|dlaa|off         auto: upscale when the target differs from the source (default);\n"
           "                             dlaa: also run DLAA at 1:1 before neural rendering; off: never\n"
           "  --sr-preset N              DLSS render preset hint (0 = default)\n"
           "\n"
           "Motion vectors and depth (the desktop has neither, so they are synthesised)\n"
           "  --mv builtin|nvof|none     builtin: GPU block matching (default); nvof: NVIDIA Optical Flow\n"
           "                             hardware (needs a build with DSCREEN_ENABLE_NVOF); none: zero motion\n"
           "  --mv-level 0..7            Finest matching level: 0 full, 1 half (default), 2 quarter resolution\n"
           "  --nvof-grid 1|2|4          Optical Flow output grid (default 1)\n"
           "  --nvof-perf slow|medium|fast\n"
           "  --depth-value F            Constant depth plane value 0..1 (default 0.5)\n"
           "  --reset-threshold F        Fraction of unmatched pixels that resets model history (default 0.5)\n"
           "\n"
           "NGX runtime\n"
           "  --ngx-path DIR             Extra folder searched for nvngx_dlssnr.dll / nvngx_dlss.dll\n"
           "  --ngx-app-id HEX           Initialise NGX with an application id instead of a project id\n"
           "  --ngx-project-id GUID      Project id used with NVSDK_NGX_D3D12_Init_with_ProjectID\n"
           "  --ngx-log 0|1|2            NGX logging: off, on (default), verbose\n"
           "  --app-data DIR             Folder for NGX logs (default: next to the executable)\n"
           "\n"
           "Window and diagnostics\n"
           "  --affinity on|off          Exclude the output window from capture (default on; off feeds back!)\n"
           "  --topmost on|off           Keep the output window above everything (default on)\n"
           "  --click-through on|off     Pass mouse input through to the desktop beneath (default on)\n"
           "  --redirection-bitmap on|off\n"
           "                             Give the window a GDI redirection surface (default off; diagnostic)\n"
           "  --adapter N                DXGI adapter index (default: first NVIDIA adapter)\n"
           "  --debug-layer on|off       Enable the Direct3D 12 debug layer\n"
           "  --log-level 0..3           0 debug, 1 info (default), 2 warn, 3 error\n"
           "  --log-file PATH            Mirror the log to a file\n"
           "\n"
           "Every failure stops the program with a message; there are no silent fallbacks.\n"
           "\n"
           "Hotkeys (global, registered with RegisterHotKey)\n"
           "  Ctrl+Alt+Shift+O           Toggle between the processed and the original picture\n"
           "  Ctrl+Alt+Shift+C           Toggle the split comparison view\n"
           "  Ctrl+Alt+Shift+Q           Quit\n"
           "  Ctrl+Alt+Shift + mouse     Drag the split divider; no click, so the desktop keeps its input\n";
}

} // namespace interior
