#include "interior/options.h"

namespace interior {

std::string_view UsageText() noexcept
{
    return "DlssScreen - DLSS 5 Neural Rendering for the live desktop\n"
           "\n"
           "Usage: DlssScreen.exe [options]\n"
           "\n"
           "Capture and output\n"
           "  --list-monitors            List monitors and exit\n"
           "  --monitor primary|all|N    Source: the primary monitor (default), every monitor, or monitor N\n"
           "  --window TITLE             Work on one window instead of a monitor: the first visible one whose\n"
           "                             title contains TITLE, ignoring case. The capture follows it as it\n"
           "                             moves and gets its content even when something is in front of it;\n"
           "                             resizing it needs a new session, since the sizes are fixed at start\n"
           "  --target N                 Present on monitor N instead of the source monitor (enables upscaling)\n"
           "  --cursor auto|on|off       Include the cursor in the capture (auto: only when --target differs)\n"
           "  --capture-border on|off    Let Windows draw its capture border (default off)\n"
           "  --vsync on|off             Present synchronised to the display (default on)\n"
           "  --compare off|split|original\n"
           "                             Comparison view: split screen or the untouched capture\n"
           "  --format rgba8|rgba16f     Model colour format (default rgba8)\n"
           "\n"
           "DLSS 5 Neural Rendering (NGX feature 18, nvngx_dlssnr.dll)\n"
           "  --nr on|off                Run the neural rendering model (default on)\n"
           "  --nr-preset N              Weights to ask the model for (default 1, the only one the 310.8\n"
           "                             model carries; anything else falls back to it and says so). The\n"
           "                             panel offers this only when the model says how many it has\n"
           "  --nr-intensity F           How much of the model's work to keep, 0 to 1 (default 1). Past 1 the model\n"
           "                             makes no further difference, so 1 is the whole of it\n"
           "  --nr-style 0|1|2           0 standard, 1 natural, 2 cinematic\n"
           "  --nr-local-structure F     Local structure strength (default 1)\n"
           "  --nr-local-tone F          Local tone strength (default 1)\n"
           "  --nr-skin F                Skin structure strength, 0 upwards; -1 exactly means follow local structure\n"
           "                             (default), and nothing between -1 and 0 means anything, so the panel\n"
           "                             offers that value as a switch. This and --nr-local-structure do\n"
           "                             nothing while --nr-automask is off\n"
           "  --nr-automask on|off       Let the model detect skin itself (default on)\n"
           "  --nr-ui-correction on|off  Model UI correction (default on). The model reads a UI layer that\n"
           "                             DlssScreen does not give it, so this is inert as wired\n"
           "\n"
           "DLSS Super Resolution (NGX feature 1, nvngx_dlss.dll)\n"
           "  --sr auto|dlaa|off         auto: upscale when the target differs from the source (default);\n"
           "                             dlaa: also run DLAA at 1:1 before neural rendering; off: never.\n"
           "                             A driver that does not offer super resolution turns this off rather\n"
           "                             than stopping the session, and the panel says so\n"
           "  --sr-preset N              DLSS render preset hint (0 = default)\n"
           "\n"
           "Motion vectors and depth (the desktop has neither, so they are synthesised)\n"
           "  --mv builtin|nvof|none     builtin: GPU block matching (default); nvof: NVIDIA Optical Flow\n"
           "                             hardware (needs a build with DSCREEN_ENABLE_NVOF); none: zero motion\n"
           "  --mv-level 0..7            Finest matching level: 0 full, 1 half (default), 2 quarter resolution\n"
           "  --nvof-grid 1|2|4          Optical Flow output grid (default 1)\n"
           "  --nvof-perf slow|medium|fast\n"
           "  --depth-value F            Constant depth plane value 0..1 (default 0.5)\n"
           "  --depth-inverted on|off    Tell the model the depth plane counts the other way (default off)\n"
           "  --mv-scale-x F             What the model multiplies the horizontal motion by; any finite value.\n"
           "                             Left out, it is the ratio between the model's size and the capture's\n"
           "  --mv-scale-y F             The same for the vertical motion\n"
           "  --reset-threshold F        Fraction of unmatched pixels that resets model history (default 0.5)\n"
           "\n"
           "NGX runtime\n"
           "  --ngx-path DIR             Extra folder searched for nvngx_dlssnr.dll / nvngx_dlss.dll\n"
           "  --ngx-app-id HEX           Initialise NGX with an application id instead of a project id\n"
           "  --ngx-project-id GUID      Project id used with NVSDK_NGX_D3D12_Init_with_ProjectID\n"
           "  --ngx-log 0|1|2            NGX logging: off, on (default), verbose\n"
           "  --indicator on|off         Let the model draw its own overlay naming its version, the preset\n"
           "                             it resolved and its working size (default off; read only at start-up)\n"
           "  --cubin-cache on|off       Let the model cache its compiled kernels (default on; start-up only)\n"
           "  --app-data DIR             Folder for NGX logs (default: next to the executable)\n"
           "\n"
           "Window and diagnostics\n"
           "  --affinity on|off          Exclude the output window from capture (default on; off makes the window\n"
           "                             photograph its own output, so the panel does not offer it)\n"
           "  --topmost on|off           Keep the output window above everything (default on)\n"
           "  --click-through on|off     Pass mouse input through to the desktop beneath (default on; off makes the\n"
           "                             overlay swallow every click, so the panel does not offer it)\n"
           "  --redirection-bitmap on|off\n"
           "                             Give the window a GDI redirection surface (default off; diagnostic)\n"
           "  --adapter N                DXGI adapter index (default: first NVIDIA adapter). The panel lists the\n"
           "                             adapters it found by name rather than asking for an index\n"
           "  --debug-layer on|off       Enable the Direct3D 12 debug layer\n"
           "  --log-level 0..3           0 debug, 1 info (default), 2 warn, 3 error\n"
           "  --log-file PATH            Mirror the log to a file\n"
           "  --gui on|off               Open the control panel (default on; off leaves the overlay alone)\n"
           "  --console auto|on|off      auto: use the console it was launched from, none when there is\n"
           "                             none (a double-click opens no window); on: always make one\n"
           "\n"
           "Every failure stops the program with a message; there are no silent fallbacks.\n"
           "\n"
           "Hotkeys (global, registered with RegisterHotKey)\n"
           "  Ctrl+Alt+Shift+O           Toggle between the processed and the original picture\n"
           "  Ctrl+Alt+Shift+C           Toggle the split comparison view\n"
           "  Ctrl+Alt+Shift+Q           Quit\n"
           "  Ctrl+Alt+Shift + mouse     Drag the split divider; no click, so the desktop keeps its input\n";
}

} // namespace interior
